name: Generate Weekly Post

on:
  schedule:
    - cron: '0 0 * * 5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Generate Weekly Post
      run: |
          START_DATE="2023-12-10"
          TODAY=$(date +'%Y-%m-%d')
          # 计算周刊的期数
          WEEKLY_NUMBER=$((($(date -d $TODAY +%s) - $(date -d $START_DATE +%s)) / 604800 + 1 +36))
          FILE_NAME="Weekly-${WEEKLY_NUMBER}"
        
          # 创建 index.md 并写入内容
          {
            echo "---"
            echo 'title: "Weekly"'
            CURRENT_TIME=$(date +'%Y-%m-%d %H:%M:%S')
            echo "date: ${CURRENT_TIME}"
            echo "tags: []"
            echo "draft: true"
            echo "---"
          } > "./content/${FILE_NAME}.md"
          ls -l "./content/${FILE_NAME}.md"

    - name: Commit and Push
      run: |
        git config --global user.name '${{ secrets.GIT_USER_NAME }}'
        git config --global user.email '${{ secrets.GIT_USER_EMAIL }}'
        git add ./content/${FILE_NAME}.md
        git commit -m "Add Weekly post"
        git push
