name = "Popsicle"
license = "MIT"
licenselink = "https://github.com/victoriadrake/hugo-theme-quint/blob/master/LICENSE"
description = "A minimalist theme with a light airy feel, site search, built-in image banners, and automatic dark and light modes."
homepage = "https://github.com/huyixi/weekly"
demosite = "https://weekly.huyixi.com/"
tags = ["responsive", "minimal", "light", "personal"]
features = ["light mode", "image banners"]
min_version = "0.125.4"

[author]
name = "huyixi"
homepage = "https://huyixi.com"
